spring.application.name: spring-boot-kotlin-cloud-run
spring:
  datasource:
    username: postgres
    password: postgres
  cloud:
    gcp:
      sql:
        instance-connection-name: persian-java-talk:us-central1:postgres-cloud-run
        database-name: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /card-service